### ISSUE TITLE
About the test Function in eval.py

### ISSUE THREAD

**Issue by zhaoxin94** [VisionLearningGroup/DANCE#4]
Hi, thanks very much for your wonderful work about UniDA.

I have a question about the test Function in eval.py:

- In the line 32-33. You let the prediction of some samples equal to n_share. But I think this may not be correct in some conditions. For example, In the OPDA setting of Office31, the n_share (10)th class is included in the source label set (0 - 19). And this may make the computation of the unkown class accuracy be wrong (line 38).

I don’t know if I misunderstood the code. Thanks very much and hope to get your reply.

**Comment by ksaito-ut** [comment]
Hi, thanks so much for your feedback. 

I checked the code and found that the implementation is correct because of the indexing in lines 37 and 38. 

For example, class_list has [0-9, 20] and the unknown label is 20, pred has 10 for unknown class prediction. 
By the indexing in a line 38, we see the correspondence between label 20 and prediction 10.  

But, I agree that this part is a little confusing. I will update some parts or add comments for a better explanation. 

Thanks a lot!

**Comment by zhaoxin94** [comment]
Hi, thanks for your reply. But I still have some confusions in my mind.

I understand the correspondence between label 20 (unknown class) and prediction 10 by the indexing in line 37 and 38.

But for OPDA setting (office31), the class 10 is included in source label set ([0-19]).  So, There is also a correspondece between label 10 (source class) and prediction 10.

In some conditions, classsifer may classify some unknown samples to 10th calss. And this may make the computation of the unkown class accuracy be wrong (line 38).

In a word, there will be two conditions for the the prediction of unknown samples be 10:
1) entropy greater than threshold  2) classify to 10 by classifier

 We don't need the second condition, because this will casue the unknown class accuracy be wrong.

Do I make myself clear?

I don’t know if I misunderstood the code. Thanks very much and hope to get your reply.

**Comment by ksaito-ut** [comment]
I got your point. As you mention, the current evaluation is not accurate in OPDA setting. 
I will update the code and results.

Thanks a lot!

**Comment by zhaoxin94** [comment]
Thanks for your quick reply!

Look forward to your updated version.

**Comment by silvia1993** [comment]
Hi, has this problem been solved? 
I notice a commit on 9th December.

Thanks!

**Comment by zhaoxin94** [comment]
Hi, I think this problem has been sovled by the commit on 9th December.
