### ISSUE TITLE
About the evaluation metric 

### ISSUE THREAD

**Issue by Solacex** [VisionLearningGroup/DANCE#6]
Hello, Thanks for your interesting and inspiring work~

Recently,  [1] and [2] proposed a new metric, harmonic mean of Known ACC and Unknown ACC, to better evaluate the capability on identifying known samples and unknown samples. 

Will you consider reporting the results with this metric? Or could you release the model trained with the proposed method(DANCE) ?. 

[1] Learning to Detect Open Classes for Universal Domain Adaptation
[2] On the Effectiveness of Image Rotation for Open Set Domain Adaptation

**Comment by ksaito-ut** [comment]
Hi, I do not plan to release the models. I think it is easy to compute the score from this implementation.

**Comment by Solacex** [comment]
OK, Thanks for your response~
